### ISSUE TITLE
Decrypt an unserialized value

### ISSUE THREAD

**Issue by mauricius** [ohseesoftware/laravel-assert-encrypted#5]
Hi, it's me again!

The package works great, but it only supports decryption of serialized values, since the `crypt/decrypt` functions use `unserialize = true` by default (see https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/helpers.php#L372).

However in Laravel 8 they added a new `encrypted` attribute casting (see https://laravel.com/docs/8.x/eloquent-mutators#attribute-casting) which automatically encrypts/decrypts values on models. Under the hood they use the `encryptString/decryptString` methods of the `Encrypter` class which do not serialize the attribute.

Would you accept a PR that adds support for unserialized encrypted values? I was thinking to add an api along these lines:
- keep the `assertEncrypted` function to avoid breaking changes, but make it use a new `assertEncryptedSerialized`
- add a new `assertEncryptedSerialized` with the same logic of the current `assertEncrypted`
- add a brand new `assertEncryptedUnserialized` that uses `encryptString/decryptString`

The only downside of this approach is that you can't make assertions when both serialized/unserialized values are used on the same table.

Thanks for the package and for your time!

**Comment by owenconti** [comment]
Hi @mauricius,

I would be fine with a PR implementing that plan!

**Comment by owenconti** [comment]
@mauricius Thank you for this!
